'use client'

/**
 * @fileoverview 月度成本分攤報告頁面
 * @description
 *   月度報告管理頁面：
 *   - 報告歷史列表
 *   - 報告生成入口
 *   - 下載功能（Excel/PDF）
 *
 * @module src/app/(dashboard)/reports/monthly
 * @since Epic 7 - Story 7.10 (月度成本分攤報告)
 * @lastModified 2025-12-20
 *
 * @features
 *   - AC1: 月度報告生成入口
 *   - AC2: 報告內容完整性
 *   - AC3: 多格式匯出
 *   - AC4: 報告歷史管理
 *
 * @dependencies
 *   - @/hooks/use-monthly-report - 報告 Hook
 *   - @/components/reports/MonthlyReportDialog - 生成對話框
 */

import * as React from 'react'
import { format } from 'date-fns'
import { useLocale, useTranslations } from 'next-intl'
import { enUS, zhTW } from 'date-fns/locale'
import {
  FileSpreadsheet,
  FileText,
  Clock,
  User,
  Bot,
  AlertCircle,
  Loader2,
} from 'lucide-react'

import { Card, CardContent } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import { MonthlyReportDialog } from '@/components/reports/MonthlyReportDialog'
import {
  useMonthlyReports,
  useDownloadMonthlyReport,
} from '@/hooks/use-monthly-report'
import type { MonthlyReportRecord, ReportFormat } from '@/types/monthly-report'

// ============================================================
// Status Badge Component
// ============================================================

interface StatusBadgeProps {
  status: string
  t: (key: string) => string
}

function StatusBadge({ status, t }: StatusBadgeProps) {
  const config: Record<
    string,
    { labelKey: string; variant: 'default' | 'secondary' | 'outline' | 'destructive' }
  > = {
    COMPLETED: { labelKey: 'completed', variant: 'default' },
    GENERATING: { labelKey: 'generating', variant: 'secondary' },
    PENDING: { labelKey: 'pending', variant: 'outline' },
    FAILED: { labelKey: 'failed', variant: 'destructive' },
  }

  const { labelKey, variant } = config[status] || config.PENDING
  return <Badge variant={variant}>{t(`monthly.status.${labelKey}`)}</Badge>
}

// ============================================================
// Report Card Component
// ============================================================

interface ReportCardProps {
  report: MonthlyReportRecord
  onDownload: (id: string, format: ReportFormat) => void
  isDownloading: boolean
  t: (key: string) => string
  dateLocale: typeof zhTW
}

function ReportCard({ report, onDownload, isDownloading, t, dateLocale }: ReportCardProps) {
  return (
    <Card>
      <CardContent className="p-6">
        <div className="flex items-start justify-between">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <h3 className="text-lg font-semibold">{report.reportMonth}</h3>
              <StatusBadge status={report.status} t={t} />
              {report.isAutoGenerated && (
                <Badge variant="outline" className="gap-1">
                  <Bot className="h-3 w-3" />
                  {t('monthly.autoGenerated')}
                </Badge>
              )}
            </div>

            {report.status === 'COMPLETED' && (
              <div className="flex gap-4 text-sm text-muted-foreground">
                <span>
                  {t('monthly.totalCost')}: ${report.totalCost?.toFixed(2)}
                </span>
                <span>
                  {t('monthly.totalVolume')}: {report.totalVolume?.toLocaleString()}
                </span>
                <span>{t('monthly.cityCount')}: {report.cityCount}</span>
              </div>
            )}

            <div className="flex items-center gap-4 text-xs text-muted-foreground">
              {report.generatedAt && (
                <span className="flex items-center gap-1">
                  <Clock className="h-3 w-3" />
                  {format(
                    new Date(report.generatedAt),
                    'yyyy/MM/dd HH:mm',
                    { locale: dateLocale }
                  )}
                </span>
              )}
              {report.generatedByName && (
                <span className="flex items-center gap-1">
                  <User className="h-3 w-3" />
                  {report.generatedByName}
                </span>
              )}
            </div>

            {report.status === 'FAILED' && report.errorMessage && (
              <p className="text-sm text-destructive flex items-center gap-1">
                <AlertCircle className="h-4 w-4" />
                {report.errorMessage}
              </p>
            )}
          </div>

          {report.status === 'COMPLETED' && (
            <div className="flex gap-2">
              {report.excelAvailable && (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => onDownload(report.id, 'excel')}
                  disabled={isDownloading}
                >
                  {isDownloading ? (
                    <Loader2 className="h-4 w-4 mr-1 animate-spin" />
                  ) : (
                    <FileSpreadsheet className="h-4 w-4 mr-1 text-green-600" />
                  )}
                  Excel
                </Button>
              )}
              {report.pdfAvailable && (
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => onDownload(report.id, 'pdf')}
                  disabled={isDownloading}
                >
                  {isDownloading ? (
                    <Loader2 className="h-4 w-4 mr-1 animate-spin" />
                  ) : (
                    <FileText className="h-4 w-4 mr-1 text-red-600" />
                  )}
                  PDF
                </Button>
              )}
            </div>
          )}

          {report.status === 'GENERATING' && (
            <div className="flex items-center gap-2 text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" />
              <span className="text-sm">{t('monthly.generatingText')}</span>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  )
}

// ============================================================
// Loading Skeleton
// ============================================================

function ReportListSkeleton() {
  return (
    <div className="grid gap-4">
      {Array.from({ length: 3 }).map((_, i) => (
        <Card key={i}>
          <CardContent className="p-6">
            <Skeleton className="h-20 w-full" />
          </CardContent>
        </Card>
      ))}
    </div>
  )
}

// ============================================================
// Empty State
// ============================================================

interface EmptyStateProps {
  t: (key: string) => string
}

function EmptyState({ t }: EmptyStateProps) {
  return (
    <Card>
      <CardContent className="p-12 text-center">
        <p className="text-muted-foreground mb-4">{t('monthly.emptyState')}</p>
        <MonthlyReportDialog
          trigger={<Button>{t('monthly.generateFirst')}</Button>}
        />
      </CardContent>
    </Card>
  )
}

// ============================================================
// Main Page Component
// ============================================================

/**
 * 月度成本分攤報告頁面
 */
export default function MonthlyReportsPage() {
  const t = useTranslations('reports')
  const locale = useLocale()
  const dateLocale = locale === 'zh-TW' ? zhTW : enUS

  const { reports, isLoading, error } = useMonthlyReports()
  const downloadMutation = useDownloadMonthlyReport()

  const handleDownload = (reportId: string, format: ReportFormat) => {
    downloadMutation.mutate({ reportId, format })
  }

  if (error) {
    return (
      <div className="container mx-auto py-6">
        <div className="flex items-center justify-center h-64">
          <p className="text-destructive">{t('monthly.loadError')}</p>
        </div>
      </div>
    )
  }

  return (
    <div className="container mx-auto py-6 space-y-6">
      {/* 頁面標題 */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">{t('monthly.title')}</h1>
          <p className="text-muted-foreground">
            {t('monthly.description')}
          </p>
        </div>
        <MonthlyReportDialog />
      </div>

      {/* 報告列表 */}
      {isLoading ? (
        <ReportListSkeleton />
      ) : reports.length === 0 ? (
        <EmptyState t={t} />
      ) : (
        <div className="grid gap-4">
          {reports.map((report) => (
            <ReportCard
              key={report.id}
              report={report}
              onDownload={handleDownload}
              isDownloading={downloadMutation.isPending}
              t={t}
              dateLocale={dateLocale}
            />
          ))}
        </div>
      )}
    </div>
  )
}
