/**
 * @fileoverview 月度成本分攤報告類型定義
 * @description
 *   定義月度報告相關的所有類型：
 *   - 報告數據結構
 *   - API 請求/響應類型
 *   - 組件屬性類型
 *
 * @module src/types/monthly-report
 * @since Epic 7 - Story 7.10
 * @lastModified 2025-12-20
 */

// ============================================================
// Report Status Types
// ============================================================

/**
 * 報告生成狀態
 */
export type ReportStatus = 'PENDING' | 'GENERATING' | 'COMPLETED' | 'FAILED';

/**
 * 報告狀態配置
 */
export interface ReportStatusConfig {
  label: string;
  variant: 'default' | 'secondary' | 'outline' | 'destructive';
  description: string;
}

/**
 * 報告狀態對照表
 */
export const REPORT_STATUS_CONFIG: Record<ReportStatus, ReportStatusConfig> = {
  PENDING: {
    label: '待處理',
    variant: 'outline',
    description: '報告等待生成',
  },
  GENERATING: {
    label: '生成中',
    variant: 'secondary',
    description: '報告正在生成',
  },
  COMPLETED: {
    label: '已完成',
    variant: 'default',
    description: '報告已成功生成',
  },
  FAILED: {
    label: '失敗',
    variant: 'destructive',
    description: '報告生成失敗',
  },
};

// ============================================================
// Report Data Types
// ============================================================

/**
 * 月度報告摘要
 */
export interface MonthlyReportSummary {
  /** 總成本 (USD) */
  totalCost: number;
  /** 總處理量 */
  totalVolume: number;
  /** AI 成本 */
  totalAiCost: number;
  /** 人工成本（估算） */
  totalLaborCost: number;
  /** 平均單位成本 */
  avgCostPerDocument: number;
  /** 城市數量 */
  cityCount: number;
  /** 與上月比較 */
  comparedToPreviousMonth: {
    /** 成本變化百分比 */
    costChange: number;
    /** 處理量變化百分比 */
    volumeChange: number;
    /** 單位成本變化百分比 */
    costPerDocChange: number;
  };
}

/**
 * 城市成本明細項目
 */
export interface CityBreakdownItem {
  /** 城市代碼 */
  cityCode: string;
  /** 城市名稱 */
  cityName: string;
  /** 區域名稱 */
  regionName?: string;
  /** 處理量 */
  volume: number;
  /** 處理量占比 (%) */
  volumePercentage: number;
  /** AI 成本 */
  aiCost: number;
  /** 人工成本 */
  laborCost: number;
  /** 總成本 */
  totalCost: number;
  /** 成本占比 (%) */
  costPercentage: number;
  /** 單位成本 */
  costPerDocument: number;
  /** 與上月比較 */
  comparedToPreviousMonth: {
    costChange: number;
    volumeChange: number;
  };
}

/**
 * API 成本明細項目
 */
export interface ApiCostBreakdownItem {
  /** API 供應商 */
  provider: string;
  /** 調用次數 */
  calls: number;
  /** Token 使用量 */
  tokens: {
    input: number;
    output: number;
  };
  /** 成本 (USD) */
  cost: number;
  /** 占比 (%) */
  percentage: number;
}

/**
 * 每日趨勢項目
 */
export interface DailyTrendItem {
  /** 日期 (YYYY-MM-DD) */
  date: string;
  /** 處理量 */
  volume: number;
  /** 成本 (USD) */
  cost: number;
}

/**
 * 完整月度報告數據
 */
export interface MonthlyReportData {
  /** 報告月份 (YYYY-MM) */
  reportMonth: string;
  /** 生成時間 */
  generatedAt: string;
  /** 摘要數據 */
  summary: MonthlyReportSummary;
  /** 城市明細 */
  cityBreakdown: CityBreakdownItem[];
  /** API 成本明細 */
  apiCostBreakdown: ApiCostBreakdownItem[];
  /** 每日趨勢 */
  dailyTrend: DailyTrendItem[];
}

// ============================================================
// Report Record Types
// ============================================================

/**
 * 報告記錄（列表項目）
 */
export interface MonthlyReportRecord {
  /** 報告 ID */
  id: string;
  /** 報告月份 (YYYY-MM) */
  reportMonth: string;
  /** 報告狀態 */
  status: ReportStatus;
  /** 總成本 */
  totalCost?: number;
  /** 總處理量 */
  totalVolume?: number;
  /** 城市數量 */
  cityCount?: number;
  /** Excel 報告是否可用 */
  excelAvailable: boolean;
  /** PDF 報告是否可用 */
  pdfAvailable: boolean;
  /** 生成時間 */
  generatedAt?: string;
  /** 生成者 ID */
  generatedBy?: string;
  /** 生成者名稱 */
  generatedByName?: string;
  /** 是否自動生成 */
  isAutoGenerated: boolean;
  /** 錯誤訊息 */
  errorMessage?: string;
  /** 創建時間 */
  createdAt: string;
}

// ============================================================
// API Request Types
// ============================================================

/**
 * 報告格式
 */
export type ReportFormat = 'excel' | 'pdf';

/**
 * 生成報告請求
 */
export interface MonthlyReportGenerateRequest {
  /** 月份 (YYYY-MM) */
  month: string;
  /** 匯出格式 */
  formats: ReportFormat[];
  /** 是否發送通知 */
  sendNotification?: boolean;
}

/**
 * 報告歷史查詢參數
 */
export interface MonthlyReportListParams {
  /** 頁碼 */
  page?: number;
  /** 每頁數量 */
  pageSize?: number;
}

/**
 * 報告下載參數
 */
export interface MonthlyReportDownloadParams {
  /** 報告 ID */
  reportId: string;
  /** 下載格式 */
  format: ReportFormat;
}

// ============================================================
// API Response Types
// ============================================================

/**
 * 報告歷史列表響應
 */
export interface MonthlyReportListResponse {
  success: boolean;
  data: MonthlyReportRecord[];
  pagination: {
    total: number;
    page: number;
    pageSize: number;
  };
}

/**
 * 生成報告響應
 */
export interface MonthlyReportGenerateResponse {
  success: boolean;
  data: MonthlyReportRecord;
}

/**
 * 報告下載響應
 */
export interface ReportDownloadResponse {
  success: boolean;
  data: {
    /** 下載連結 */
    downloadUrl: string;
    /** 過期時間 */
    expiresAt: string;
    /** 檔案名稱 */
    fileName: string;
  };
}

/**
 * API 錯誤響應
 */
export interface MonthlyReportErrorResponse {
  success: false;
  error: string;
}

// ============================================================
// Component Props Types
// ============================================================

/**
 * 月度報告對話框屬性
 */
export interface MonthlyReportDialogProps {
  /** 觸發元素 */
  trigger?: React.ReactNode;
  /** 打開狀態 */
  open?: boolean;
  /** 狀態變更回調 */
  onOpenChange?: (open: boolean) => void;
}

/**
 * 報告卡片屬性
 */
export interface ReportCardProps {
  /** 報告記錄 */
  report: MonthlyReportRecord;
  /** 下載回調 */
  onDownload: (reportId: string, format: ReportFormat) => void;
}

/**
 * 報告歷史列表屬性
 */
export interface ReportHistoryListProps {
  /** 報告列表 */
  reports: MonthlyReportRecord[];
  /** 是否載入中 */
  isLoading?: boolean;
  /** 下載回調 */
  onDownload: (reportId: string, format: ReportFormat) => void;
}

// ============================================================
// Constants
// ============================================================

/**
 * 預設人工審核成本（USD/次）
 */
export const DEFAULT_COST_PER_MANUAL_REVIEW = 0.50;

/**
 * 預設人工審核比例
 */
export const DEFAULT_MANUAL_REVIEW_RATE = 0.15;

/**
 * 報告有效期（天）
 */
export const REPORT_EXPIRY_DAYS = 90;

/**
 * 預設每頁報告數量
 */
export const DEFAULT_REPORTS_PAGE_SIZE = 12;

/**
 * 可用的報告格式
 */
export const AVAILABLE_REPORT_FORMATS: ReportFormat[] = ['excel', 'pdf'];

// ============================================================
// Utility Functions
// ============================================================

/**
 * 獲取報告狀態配置
 */
export function getReportStatusConfig(status: ReportStatus): ReportStatusConfig {
  return REPORT_STATUS_CONFIG[status];
}

/**
 * 格式化月份顯示
 */
export function formatReportMonth(month: string): string {
  const [year, monthNum] = month.split('-');
  return `${year} 年 ${parseInt(monthNum)} 月`;
}

/**
 * 計算人工成本估算
 */
export function estimateLaborCost(
  volume: number,
  costPerReview: number = DEFAULT_COST_PER_MANUAL_REVIEW,
  reviewRate: number = DEFAULT_MANUAL_REVIEW_RATE
): number {
  return volume * reviewRate * costPerReview;
}
