/**
 * @fileoverview Excel 報告國際化翻譯常數
 * @description
 *   提供 Excel 報告生成時的多語言支援。
 *   由於服務端代碼無法使用 next-intl 的 useTranslations hook，
 *   這裡採用靜態翻譯常數的方式。
 *
 * @module src/lib/reports/excel-i18n
 * @since Epic 17 - i18n Implementation
 * @lastModified 2026-01-20
 *
 * @features
 *   - 支援 en, zh-TW, zh-CN 三種語言
 *   - 包含 Excel 工作表名稱、表頭、標籤等翻譯
 *   - 可由 locale 參數動態選擇語言
 */

import type { DocumentType, DocumentSubtype } from '@/types/document-format';

// ============================================================================
// Types
// ============================================================================

export type ExcelLocale = 'en' | 'zh-TW' | 'zh-CN';

export interface ExcelI18nStrings {
  // 工作表名稱
  sheets: {
    summary: string;
    companies: string;
    formats: string;
    terms: string;
  };
  // 摘要工作表
  summary: {
    headers: {
      item: string;
      value: string;
    };
    labels: {
      batchId: string;
      batchName: string;
      startedAt: string;
      completedAt: string;
      companyCount: string;
      formatCount: string;
      uniqueTermCount: string;
      termOccurrenceCount: string;
      generatedAt: string;
      generatedBy: string;
    };
  };
  // 公司列表工作表
  companies: {
    headers: {
      index: string;
      companyId: string;
      companyName: string;
      nameVariants: string;
      fileCount: string;
      formatCount: string;
      termCount: string;
    };
  };
  // 格式列表工作表
  formats: {
    headers: {
      index: string;
      formatId: string;
      companyName: string;
      documentType: string;
      documentSubtype: string;
      formatName: string;
      fileCount: string;
      termCount: string;
    };
  };
  // 術語列表工作表
  terms: {
    headers: {
      index: string;
      companyName: string;
      formatType: string;
      term: string;
      frequency: string;
      examples: string;
      suggestedCategory: string;
    };
  };
  // 文件類型標籤
  documentTypes: Record<DocumentType, string>;
  // 文件子類型標籤
  documentSubtypes: Record<DocumentSubtype, string>;
  // 報告文件名前綴
  reportFileNamePrefix: string;
  // 通用標籤
  common: {
    notAvailable: string;
    none: string;
  };
}

// ============================================================================
// Translations
// ============================================================================

const translations: Record<ExcelLocale, ExcelI18nStrings> = {
  en: {
    sheets: {
      summary: 'Summary',
      companies: 'Companies',
      formats: 'Formats',
      terms: 'Terms',
    },
    summary: {
      headers: {
        item: 'Item',
        value: 'Value',
      },
      labels: {
        batchId: 'Batch ID',
        batchName: 'Batch Name',
        startedAt: 'Started At',
        completedAt: 'Completed At',
        companyCount: 'Company Count',
        formatCount: 'Format Count',
        uniqueTermCount: 'Unique Term Count',
        termOccurrenceCount: 'Term Occurrence Count',
        generatedAt: 'Report Generated At',
        generatedBy: 'Generated By',
      },
    },
    companies: {
      headers: {
        index: 'No.',
        companyId: 'Company ID',
        companyName: 'Company Name',
        nameVariants: 'Name Variants',
        fileCount: 'File Count',
        formatCount: 'Format Count',
        termCount: 'Term Count',
      },
    },
    formats: {
      headers: {
        index: 'No.',
        formatId: 'Format ID',
        companyName: 'Company',
        documentType: 'Document Type',
        documentSubtype: 'Document Subtype',
        formatName: 'Format Name',
        fileCount: 'File Count',
        termCount: 'Term Count',
      },
    },
    terms: {
      headers: {
        index: 'No.',
        companyName: 'Company',
        formatType: 'Format Type',
        term: 'Term',
        frequency: 'Frequency',
        examples: 'Examples',
        suggestedCategory: 'Suggested Category',
      },
    },
    documentTypes: {
      INVOICE: 'Invoice',
      DEBIT_NOTE: 'Debit Note',
      CREDIT_NOTE: 'Credit Note',
      STATEMENT: 'Statement',
      QUOTATION: 'Quotation',
      BILL_OF_LADING: 'Bill of Lading',
      CUSTOMS_DECLARATION: 'Customs Declaration',
      OTHER: 'Other',
    },
    documentSubtypes: {
      OCEAN_FREIGHT: 'Ocean Freight',
      AIR_FREIGHT: 'Air Freight',
      LAND_TRANSPORT: 'Land Transport',
      CUSTOMS_CLEARANCE: 'Customs Clearance',
      WAREHOUSING: 'Warehousing',
      GENERAL: 'General',
    },
    reportFileNamePrefix: 'Terms-Report',
    common: {
      notAvailable: 'N/A',
      none: '-',
    },
  },
  'zh-TW': {
    sheets: {
      summary: '摘要',
      companies: '公司列表',
      formats: '格式列表',
      terms: '術語列表',
    },
    summary: {
      headers: {
        item: '項目',
        value: '值',
      },
      labels: {
        batchId: '批次 ID',
        batchName: '批次名稱',
        startedAt: '開始時間',
        completedAt: '完成時間',
        companyCount: '公司數量',
        formatCount: '格式數量',
        uniqueTermCount: '唯一術語數',
        termOccurrenceCount: '術語出現次數',
        generatedAt: '報告產生時間',
        generatedBy: '產生者',
      },
    },
    companies: {
      headers: {
        index: '序號',
        companyId: '公司 ID',
        companyName: '公司名稱',
        nameVariants: '名稱變體',
        fileCount: '文件數量',
        formatCount: '格式數量',
        termCount: '術語數量',
      },
    },
    formats: {
      headers: {
        index: '序號',
        formatId: '格式 ID',
        companyName: '所屬公司',
        documentType: '文件類型',
        documentSubtype: '文件子類型',
        formatName: '格式名稱',
        fileCount: '文件數量',
        termCount: '術語數量',
      },
    },
    terms: {
      headers: {
        index: '序號',
        companyName: '公司名稱',
        formatType: '格式類型',
        term: '術語',
        frequency: '出現頻率',
        examples: '範例',
        suggestedCategory: '建議分類',
      },
    },
    documentTypes: {
      INVOICE: '發票',
      DEBIT_NOTE: '借項通知單',
      CREDIT_NOTE: '貸項通知單',
      STATEMENT: '對帳單',
      QUOTATION: '報價單',
      BILL_OF_LADING: '提單',
      CUSTOMS_DECLARATION: '報關單',
      OTHER: '其他',
    },
    documentSubtypes: {
      OCEAN_FREIGHT: '海運',
      AIR_FREIGHT: '空運',
      LAND_TRANSPORT: '陸運',
      CUSTOMS_CLEARANCE: '報關',
      WAREHOUSING: '倉儲',
      GENERAL: '一般',
    },
    reportFileNamePrefix: '術語報告',
    common: {
      notAvailable: 'N/A',
      none: '-',
    },
  },
  'zh-CN': {
    sheets: {
      summary: '摘要',
      companies: '公司列表',
      formats: '格式列表',
      terms: '术语列表',
    },
    summary: {
      headers: {
        item: '项目',
        value: '值',
      },
      labels: {
        batchId: '批次 ID',
        batchName: '批次名称',
        startedAt: '开始时间',
        completedAt: '完成时间',
        companyCount: '公司数量',
        formatCount: '格式数量',
        uniqueTermCount: '唯一术语数',
        termOccurrenceCount: '术语出现次数',
        generatedAt: '报告生成时间',
        generatedBy: '生成者',
      },
    },
    companies: {
      headers: {
        index: '序号',
        companyId: '公司 ID',
        companyName: '公司名称',
        nameVariants: '名称变体',
        fileCount: '文件数量',
        formatCount: '格式数量',
        termCount: '术语数量',
      },
    },
    formats: {
      headers: {
        index: '序号',
        formatId: '格式 ID',
        companyName: '所属公司',
        documentType: '文件类型',
        documentSubtype: '文件子类型',
        formatName: '格式名称',
        fileCount: '文件数量',
        termCount: '术语数量',
      },
    },
    terms: {
      headers: {
        index: '序号',
        companyName: '公司名称',
        formatType: '格式类型',
        term: '术语',
        frequency: '出现频率',
        examples: '示例',
        suggestedCategory: '建议分类',
      },
    },
    documentTypes: {
      INVOICE: '发票',
      DEBIT_NOTE: '借项通知单',
      CREDIT_NOTE: '贷项通知单',
      STATEMENT: '对账单',
      QUOTATION: '报价单',
      BILL_OF_LADING: '提单',
      CUSTOMS_DECLARATION: '报关单',
      OTHER: '其他',
    },
    documentSubtypes: {
      OCEAN_FREIGHT: '海运',
      AIR_FREIGHT: '空运',
      LAND_TRANSPORT: '陆运',
      CUSTOMS_CLEARANCE: '报关',
      WAREHOUSING: '仓储',
      GENERAL: '一般',
    },
    reportFileNamePrefix: '术语报告',
    common: {
      notAvailable: 'N/A',
      none: '-',
    },
  },
};

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * 取得指定語言的翻譯字串
 *
 * @param locale - 語言代碼
 * @returns 對應語言的翻譯字串物件
 */
export function getExcelI18n(locale: ExcelLocale = 'en'): ExcelI18nStrings {
  return translations[locale] || translations.en;
}

/**
 * 將 next-intl 的 locale 轉換為 Excel 報告支援的 locale
 *
 * @param locale - next-intl locale (如 'en', 'zh-TW', 'zh-CN')
 * @returns Excel 報告支援的 locale
 */
export function normalizeLocale(locale: string | undefined): ExcelLocale {
  if (!locale) return 'en';

  // 直接匹配
  if (locale === 'en' || locale === 'zh-TW' || locale === 'zh-CN') {
    return locale;
  }

  // 簡化版匹配
  if (locale.startsWith('zh')) {
    // 預設使用繁體中文
    return 'zh-TW';
  }

  return 'en';
}
